$(document).ready(function(){
    $(".owl-carousel").owlCarousel({
        items:1,
        margin:10,
        loop:true,
        autoplay:true,
        autoplayTimeout:4000,
        dots:true,
    });
  });